# Этап 1: Сборка
FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Собираем статически связанный бинарник
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Этап 2: Запуск
FROM alpine:3.19

WORKDIR /app

# Устанавливаем сертификаты для HTTPS запросов
RUN apk --no-cache add ca-certificates

# Копируем бинарник из этапа сборки
COPY --from=builder /app/main .

# Переменные окружения
ENV DB_HOST=my-postgres
ENV DB_USER=myuser
ENV DB_PASSWORD=mypassword
ENV DB_NAME=mydb
ENV DB_PORT=5432

EXPOSE 8080

CMD ["./main"]